---
title: "compute_outline"
format: html
---

### Data Types

AnalogTimeSeries -\> float for each time

DigitalEventSeries

DigitalIntervalSeries

LineData

MaskData

PointData

### Data Transforms

+--------------------------+-------------------------------+-----------------------+--------------------+
| Name                     | Input                         | Output                | Params             |
+==========================+===============================+=======================+====================+
| Analog Event Threshold   | AnalogTimeSeries              | DigitalEventSeries    |                    |
+--------------------------+-------------------------------+-----------------------+--------------------+
| Analog Interval Peak     | AnalogTimeSeries              | DigitalEventSeries    |                    |
|                          |                               |                       |                    |
|                          | DigitalIntervalSeries         |                       |                    |
+--------------------------+-------------------------------+-----------------------+--------------------+
| Analog Scaling           | AnalogTimeSeries              | AnalogTimeSeries      |                    |
+--------------------------+-------------------------------+-----------------------+--------------------+
| Analog Filter            | AnalogTimeSeries              | AnalogTimeSeries      |                    |
+--------------------------+-------------------------------+-----------------------+--------------------+
| AnalogHilbertPhase       | AnalogTimeSeries              | AnalogTimeSeries      |                    |
+--------------------------+-------------------------------+-----------------------+--------------------+
| Boolean                  | DigitalIntervalSeries         | DigitalIntervalSeries |                    |
|                          |                               |                       |                    |
|                          | DigitalIntervalSeries         |                       |                    |
+--------------------------+-------------------------------+-----------------------+--------------------+
| Digital interval Group   | DigitalIntervalSeries         | DigitalIntervalSeries |                    |
+--------------------------+-------------------------------+-----------------------+--------------------+
| LineAlignment            | LineData (Single)             | LineData (Ragged)     |                    |
|                          |                               |                       |                    |
|                          | MediaData                     |                       |                    |
+--------------------------+-------------------------------+-----------------------+--------------------+
| Line Angle               | LineData (T)                  | AnalogTimeSeries (T)  |                    |
+--------------------------+-------------------------------+-----------------------+--------------------+
| Line Base Flip           | LineData (T)                  | LineData (T)          |                    |
|                          |                               |                       |                    |
|                          | PointData (just single point) |                       |                    |
+--------------------------+-------------------------------+-----------------------+--------------------+
| Line Clip                | LineData (T)                  | LineData (T)          |                    |
|                          |                               |                       |                    |
|                          | LineData (S)                  |                       |                    |
+--------------------------+-------------------------------+-----------------------+--------------------+
| Line Curvature           | LineData (T)                  | AnalogTimeSeries (T)  |                    |
+--------------------------+-------------------------------+-----------------------+--------------------+
| Line Group to Intervals  | LineData                      | DigitalIntervalSeries | EntityGroupManager |
+--------------------------+-------------------------------+-----------------------+--------------------+
| Line Index Grouping      | LineData                      | Nothing               | EntityGroupManager |
+--------------------------+-------------------------------+-----------------------+--------------------+
| Line Kalman Grouping     | LineData                      | Nothing               | EntityGroupManager |
+--------------------------+-------------------------------+-----------------------+--------------------+
| Line Min Point Dist      | LineData                      | AnalogTimeSeries      |                    |
|                          |                               |                       |                    |
|                          | PointData                     |                       |                    |
+--------------------------+-------------------------------+-----------------------+--------------------+
| Line Outlier Detection   | LineData                      | Nothing               | EntityGroupManager |
+--------------------------+-------------------------------+-----------------------+--------------------+
| Line Point Extraction    | LineData                      | PointData             |                    |
+--------------------------+-------------------------------+-----------------------+--------------------+
| Line Proximity Grouping  | LineData                      | Nothing               | EntityGroupManager |
+--------------------------+-------------------------------+-----------------------+--------------------+
| Line Resampling          | LineData                      | LineData              |                    |
+--------------------------+-------------------------------+-----------------------+--------------------+
| Line Subsegment          | LineData                      | LineData              |                    |
+--------------------------+-------------------------------+-----------------------+--------------------+
| Mask Area                | MaskData                      | AnalogTimeSeries      |                    |
+--------------------------+-------------------------------+-----------------------+--------------------+
| Mask Centroid            | MaskData                      | PointData             |                    |
+--------------------------+-------------------------------+-----------------------+--------------------+
| Mask Connected Component | MaskData                      | MaskData              |                    |
+--------------------------+-------------------------------+-----------------------+--------------------+
| Mask Hole Filling        | MaskData                      | MaskData              |                    |
+--------------------------+-------------------------------+-----------------------+--------------------+
| Median Filter            | MaskData                      | MaskData              |                    |
+--------------------------+-------------------------------+-----------------------+--------------------+
| Mask Principal Axis      | MaskData                      | LineData              |                    |
+--------------------------+-------------------------------+-----------------------+--------------------+
| Mask Skeletonize         | MaskData                      | MaskData              |                    |
+--------------------------+-------------------------------+-----------------------+--------------------+
| Mask to Line             | MaskData                      | LineData              |                    |
+--------------------------+-------------------------------+-----------------------+--------------------+
| Whisker Tracing          | MediaData                     | LineData              |                    |
|                          |                               |                       |                    |
|                          | MaskData (optional)           |                       |                    |
+--------------------------+-------------------------------+-----------------------+--------------------+
| Point Particle Filter    | PointData                     | PointData             |                    |
|                          |                               |                       |                    |
|                          | MaskData                      |                       |                    |
+--------------------------+-------------------------------+-----------------------+--------------------+
|                          |                               |                       |                    |
+--------------------------+-------------------------------+-----------------------+--------------------+
|                          |                               |                       |                    |
+--------------------------+-------------------------------+-----------------------+--------------------+
|                          |                               |                       |                    |
+--------------------------+-------------------------------+-----------------------+--------------------+

### Tableview Computers

+------------------------------------+-----------------------+-----------------------+----------------------------------------------------+--------+
| Name                               | Input                 | Time                  | Output                                             | Params |
+====================================+=======================+=======================+====================================================+========+
| Analog Slice Gatherer              | AnalogTimeSeries      | TimeFrameIndex        | std::vector\<std::vector\<float\>\>                |        |
|                                    |                       |                       |                                                    |        |
|                                    | DigitalIntervalSeries |                       | std::vector\<\> within digital interval series     |        |
+------------------------------------+-----------------------+-----------------------+----------------------------------------------------+--------+
| AnalogTimestampOffsetMultiComputer | AnalogTimeSeries      | TimeFrameIndex        | std::vector\<FixedSizeArray\>                      |        |
+------------------------------------+-----------------------+-----------------------+----------------------------------------------------+--------+
| EventInIntervalComputer            | DigitalEventSeries    | DigitalIntervalSeries | Presence - bool                                    |        |
|                                    |                       |                       |                                                    |        |
|                                    |                       |                       | Count - int                                        |        |
|                                    |                       |                       |                                                    |        |
|                                    |                       |                       | Gather - std::vector\<float\>                      |        |
|                                    |                       |                       |                                                    |        |
|                                    |                       |                       | GatherCenter - std::vector\<float\>                |        |
|                                    |                       |                       |                                                    |        |
|                                    |                       |                       | all of these also provide std::Vector\<EntityIDs\> |        |
+------------------------------------+-----------------------+-----------------------+----------------------------------------------------+--------+
| IntervalOverlapComputer            | DigitalIntervalSeries | DigitalIntervalSeries | AssignID - int                                     |        |
|                                    |                       |                       |                                                    |        |
|                                    |                       |                       | CounterOverlaps - int                              |        |
|                                    |                       |                       |                                                    |        |
|                                    |                       |                       | AssignID_Start - int                               |        |
|                                    |                       |                       |                                                    |        |
|                                    |                       |                       | AssignID_End - int                                 |        |
|                                    |                       |                       |                                                    |        |
|                                    |                       |                       | all of these also provide std::Vector\<EntityIDs\> |        |
+------------------------------------+-----------------------+-----------------------+----------------------------------------------------+--------+
| IntervalPropertyComputer           | DigitalIntervalSeries | DigitalIntervalSeries |                                                    |        |
+------------------------------------+-----------------------+-----------------------+----------------------------------------------------+--------+
| IntervalReductionComputer          | AnalogTimeSeries      | DigitalIntervalSeries |                                                    |        |
+------------------------------------+-----------------------+-----------------------+----------------------------------------------------+--------+
| LineLengthComputer                 | LineData              | TimeFrameIndex        | AnalogTimeSeries (Ragged)                          |        |
+------------------------------------+-----------------------+-----------------------+----------------------------------------------------+--------+
| LIneSamplingMultiComputer          | LineData              | TimeFrameIndex        | PointData?\                                        |        |
|                                    |                       |                       | AnalogTimeSeries(FixedSize)                        |        |
+------------------------------------+-----------------------+-----------------------+----------------------------------------------------+--------+
| LineTimestampComputer              |                       |                       |                                                    |        |
+------------------------------------+-----------------------+-----------------------+----------------------------------------------------+--------+
| TimestampInIntervalComputer        |                       |                       |                                                    |        |
+------------------------------------+-----------------------+-----------------------+----------------------------------------------------+--------+
| TimestampValueComputer             |                       |                       |                                                    |        |
+------------------------------------+-----------------------+-----------------------+----------------------------------------------------+--------+
