name: 'Linux Setup'
description: 'Setup common dependencies and environment for CI'
inputs:
  buildfolder:
    description: 'Build folder path'
    required: true
  compiler:
    description: 'Compiler to use'
    required: true
runs:
  using: 'composite'
  steps:

    - name: Restore vcpkg cache
      uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ${{ github.workspace }}/vcpkg_cache
        key: vcpkg-linux-${{ inputs.compiler }}-${{ hashFiles('vcpkg.json') }}-${{ github.run_id }}
        restore-keys: vcpkg-linux-${{ inputs.compiler }}-

    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: install-cmake
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: "~3.30.0"

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: 'ce613c41372b23b1f51333815feb3edd87ef8a8b' #2025.04.09 needed for libffi fix, highs 1.10

    - name: Export GitHub Actions cache environment variables
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.7.2
        cache: true

    - name: Set QTDIR and QtToolsPath
      shell: bash
      run: |
        echo "QTDIR=$QT_ROOT_DIR" >> "$GITHUB_ENV"
        echo "QtToolsPath=$QT_ROOT_DIR/bin" >> "$GITHUB_ENV"

    - name: Install nasm and other libraries on Linux
      shell: bash
      run: sudo apt-get install -y nasm libxi-dev libxtst-dev libxrandr-dev libomp-18-dev lcov gcovr libltdl-dev libopenblas-dev

    - name: Setup headless display
      uses: pyvista/setup-headless-display-action@v3

    - name: Install jinja2
      shell: bash
      run: pip install jinja2 setuptools
