---
title: "Whisker Tracking"
---

### Load Whiskers

| File Format | Description |
|--------------|----------------------------------------------------------|
| Janelia | Binary format output by janelia whisker tracker |
| CSV | Each row represents a 2d point (x,y) along the whisker. The points should be arranged from follicle to tip |
| HDF5 |  |

: Supported Whisker File Formats

### Load Keypoints

### Trace Button

### Length Threshold

Whisker segments below the length threshold will be discarded. Length threshold is in units of pixels

### Whisker Pad Selection

The whisker pad location in pixel coordinates. Candidate whiskers are ordered so that the base of the whisker is nearest the whisker pad. Whiskers with bases beyond some distance from the whisker pad can also be discarded.

### Head Orientation

The head orientation is the direction that the animal's nose is pointing in the image. The head orientation is used to determine the identity of the whiskers in the frame (most posterior whisker is 0, next most posterior is 1, etc).

### Number of Whiskers Selection

### Export Image and CSV Button

### Face Mask

The face mask corresponds to the part of the image belonging to the face. This can be used in several ways

-   Whisker bases can be extended to always connect to the face mask. This eliminates jitter that can occur because of fur

-   Whisker bases can be clipped to ensure that the whisker does not enter the face mask.

### Janelia Settings

### **Contact Detection**
