#ifndef COREPLOTTING_COLORMAPS_COLORMAPLUTS_HPP
#define COREPLOTTING_COLORMAPS_COLORMAPLUTS_HPP

/**
 * @file ColormapLUTs.hpp
 * @brief Lookup table data for built-in colormaps
 *
 * Each LUT is a 256-entry array of glm::vec3 (RGB, range [0,1]).
 * Data for perceptually uniform colormaps (Inferno, Viridis, Magma, Plasma)
 * is sampled from the matplotlib reference implementations.
 *
 * Simpler colormaps (Grayscale, Hot, Coolwarm) are generated algorithmically
 * at compile time.
 */

#include "Colormap.hpp"

#include <glm/glm.hpp>

#include <algorithm>
#include <array>
#include <cmath>
#include <cstddef>

namespace CorePlotting::Colormaps::detail {

// =============================================================================
// Algorithmic LUT generators (constexpr where possible)
// =============================================================================

/**
 * @brief Generate a Grayscale LUT: black (0) → white (1)
 */
inline ColormapLUT generateGrayscaleLUT()
{
    ColormapLUT lut{};
    for (std::size_t i = 0; i < LUT_SIZE; ++i) {
        float const t = static_cast<float>(i) / 255.0f;
        lut[i] = glm::vec3(t, t, t);
    }
    return lut;
}

/**
 * @brief Generate a Hot LUT: black → red → yellow → white
 *
 * Follows the classic "hot" colormap: R ramps 0→1 over [0, 0.375],
 * G ramps 0→1 over [0.375, 0.75], B ramps 0→1 over [0.75, 1.0].
 */
inline ColormapLUT generateHotLUT()
{
    ColormapLUT lut{};
    for (std::size_t i = 0; i < LUT_SIZE; ++i) {
        float const t = static_cast<float>(i) / 255.0f;

        float r = std::clamp(t / 0.375f, 0.0f, 1.0f);
        float g = std::clamp((t - 0.375f) / 0.375f, 0.0f, 1.0f);
        float b = std::clamp((t - 0.75f) / 0.25f, 0.0f, 1.0f);

        lut[i] = glm::vec3(r, g, b);
    }
    return lut;
}

/**
 * @brief Generate a Coolwarm diverging LUT: blue → white → red
 *
 * Uses a simple smooth interpolation: blue at t=0, white at t=0.5, red at t=1.
 * This is a simplified version of the Moreland diverging colormap.
 */
inline ColormapLUT generateCoolwarmLUT()
{
    ColormapLUT lut{};
    for (std::size_t i = 0; i < LUT_SIZE; ++i) {
        float const t = static_cast<float>(i) / 255.0f;

        float r, g, b;
        if (t < 0.5f) {
            // Blue → White (t: 0 → 0.5)
            float const s = t * 2.0f; // 0 → 1
            r = 0.23f + s * (1.0f - 0.23f);
            g = 0.30f + s * (1.0f - 0.30f);
            b = 0.75f + s * (1.0f - 0.75f);
        } else {
            // White → Red (t: 0.5 → 1)
            float const s = (t - 0.5f) * 2.0f; // 0 → 1
            r = 1.0f;
            g = 1.0f - s * (1.0f - 0.18f);
            b = 1.0f - s * (1.0f - 0.18f);
        }

        lut[i] = glm::vec3(r, g, b);
    }
    return lut;
}

// =============================================================================
// Sampled LUTs for perceptually uniform colormaps
// =============================================================================
// These are subsampled (every 16th entry from 4096-point reference) then
// linearly interpolated at lookup time. 16 control points × 3 channels.
// Full 256-entry LUTs are generated by linear interpolation at init time.

/**
 * @brief Control point for LUT interpolation
 */
struct ControlPoint {
    float t;  ///< Position in [0, 1]
    float r;  ///< Red channel
    float g;  ///< Green channel
    float b;  ///< Blue channel
};

/**
 * @brief Interpolate control points into a full 256-entry LUT
 */
template<std::size_t N>
inline ColormapLUT interpolateLUT(std::array<ControlPoint, N> const & points)
{
    ColormapLUT lut{};
    for (std::size_t i = 0; i < LUT_SIZE; ++i) {
        float const t = static_cast<float>(i) / 255.0f;

        // Find the two control points bracketing t
        std::size_t idx = 0;
        for (std::size_t j = 1; j < N; ++j) {
            if (points[j].t >= t) {
                idx = j - 1;
                break;
            }
            idx = j - 1;
        }
        if (idx >= N - 1) idx = N - 2;

        float const t0 = points[idx].t;
        float const t1 = points[idx + 1].t;
        float const frac = (t1 > t0) ? (t - t0) / (t1 - t0) : 0.0f;
        float const f = std::clamp(frac, 0.0f, 1.0f);

        lut[i] = glm::vec3(
            points[idx].r + f * (points[idx + 1].r - points[idx].r),
            points[idx].g + f * (points[idx + 1].g - points[idx].g),
            points[idx].b + f * (points[idx + 1].b - points[idx].b));
    }
    return lut;
}

// Inferno: 17 control points sampled from matplotlib's Inferno
inline constexpr std::array<ControlPoint, 17> INFERNO_POINTS = {{
    {0.000f, 0.001f, 0.000f, 0.014f},
    {0.063f, 0.046f, 0.030f, 0.150f},
    {0.125f, 0.126f, 0.047f, 0.324f},
    {0.188f, 0.212f, 0.054f, 0.446f},
    {0.250f, 0.302f, 0.063f, 0.499f},
    {0.313f, 0.392f, 0.072f, 0.504f},
    {0.375f, 0.478f, 0.090f, 0.475f},
    {0.438f, 0.560f, 0.118f, 0.423f},
    {0.500f, 0.638f, 0.157f, 0.362f},
    {0.563f, 0.712f, 0.205f, 0.295f},
    {0.625f, 0.781f, 0.265f, 0.226f},
    {0.688f, 0.843f, 0.337f, 0.159f},
    {0.750f, 0.899f, 0.419f, 0.101f},
    {0.813f, 0.940f, 0.516f, 0.055f},
    {0.875f, 0.964f, 0.625f, 0.039f},
    {0.938f, 0.974f, 0.744f, 0.132f},
    {1.000f, 0.988f, 0.998f, 0.645f},
}};

// Viridis: 17 control points sampled from matplotlib's Viridis
inline constexpr std::array<ControlPoint, 17> VIRIDIS_POINTS = {{
    {0.000f, 0.267f, 0.004f, 0.329f},
    {0.063f, 0.283f, 0.084f, 0.420f},
    {0.125f, 0.278f, 0.148f, 0.497f},
    {0.188f, 0.260f, 0.207f, 0.555f},
    {0.250f, 0.233f, 0.264f, 0.595f},
    {0.313f, 0.202f, 0.320f, 0.620f},
    {0.375f, 0.171f, 0.376f, 0.631f},
    {0.438f, 0.143f, 0.430f, 0.627f},
    {0.500f, 0.127f, 0.483f, 0.607f},
    {0.563f, 0.135f, 0.537f, 0.572f},
    {0.625f, 0.180f, 0.590f, 0.520f},
    {0.688f, 0.262f, 0.640f, 0.450f},
    {0.750f, 0.370f, 0.687f, 0.366f},
    {0.813f, 0.497f, 0.726f, 0.270f},
    {0.875f, 0.638f, 0.756f, 0.163f},
    {0.938f, 0.789f, 0.774f, 0.075f},
    {1.000f, 0.993f, 0.906f, 0.144f},
}};

// Magma: 17 control points sampled from matplotlib's Magma
inline constexpr std::array<ControlPoint, 17> MAGMA_POINTS = {{
    {0.000f, 0.001f, 0.000f, 0.014f},
    {0.063f, 0.046f, 0.027f, 0.147f},
    {0.125f, 0.118f, 0.042f, 0.334f},
    {0.188f, 0.202f, 0.044f, 0.475f},
    {0.250f, 0.288f, 0.059f, 0.530f},
    {0.313f, 0.375f, 0.073f, 0.550f},
    {0.375f, 0.466f, 0.087f, 0.548f},
    {0.438f, 0.554f, 0.115f, 0.530f},
    {0.500f, 0.639f, 0.159f, 0.498f},
    {0.563f, 0.718f, 0.215f, 0.465f},
    {0.625f, 0.789f, 0.282f, 0.439f},
    {0.688f, 0.851f, 0.361f, 0.425f},
    {0.750f, 0.900f, 0.451f, 0.430f},
    {0.813f, 0.936f, 0.550f, 0.462f},
    {0.875f, 0.960f, 0.656f, 0.522f},
    {0.938f, 0.976f, 0.771f, 0.614f},
    {1.000f, 0.987f, 0.991f, 0.750f},
}};

// Plasma: 17 control points sampled from matplotlib's Plasma
inline constexpr std::array<ControlPoint, 17> PLASMA_POINTS = {{
    {0.000f, 0.050f, 0.030f, 0.528f},
    {0.063f, 0.160f, 0.019f, 0.577f},
    {0.125f, 0.261f, 0.010f, 0.614f},
    {0.188f, 0.352f, 0.008f, 0.638f},
    {0.250f, 0.439f, 0.019f, 0.641f},
    {0.313f, 0.521f, 0.053f, 0.622f},
    {0.375f, 0.597f, 0.098f, 0.585f},
    {0.438f, 0.667f, 0.147f, 0.536f},
    {0.500f, 0.730f, 0.200f, 0.478f},
    {0.563f, 0.786f, 0.257f, 0.416f},
    {0.625f, 0.835f, 0.319f, 0.352f},
    {0.688f, 0.878f, 0.385f, 0.289f},
    {0.750f, 0.915f, 0.456f, 0.224f},
    {0.813f, 0.944f, 0.536f, 0.158f},
    {0.875f, 0.964f, 0.625f, 0.095f},
    {0.938f, 0.974f, 0.725f, 0.047f},
    {1.000f, 0.940f, 0.975f, 0.131f},
}};

// =============================================================================
// LUT singletons (lazy-initialized)
// =============================================================================

inline ColormapLUT const & infernoLUT()
{
    static ColormapLUT const lut = interpolateLUT(INFERNO_POINTS);
    return lut;
}

inline ColormapLUT const & viridisLUT()
{
    static ColormapLUT const lut = interpolateLUT(VIRIDIS_POINTS);
    return lut;
}

inline ColormapLUT const & magmaLUT()
{
    static ColormapLUT const lut = interpolateLUT(MAGMA_POINTS);
    return lut;
}

inline ColormapLUT const & plasmaLUT()
{
    static ColormapLUT const lut = interpolateLUT(PLASMA_POINTS);
    return lut;
}

inline ColormapLUT const & grayscaleLUT()
{
    static ColormapLUT const lut = generateGrayscaleLUT();
    return lut;
}

inline ColormapLUT const & hotLUT()
{
    static ColormapLUT const lut = generateHotLUT();
    return lut;
}

inline ColormapLUT const & coolwarmLUT()
{
    static ColormapLUT const lut = generateCoolwarmLUT();
    return lut;
}

} // namespace CorePlotting::Colormaps::detail

#endif // COREPLOTTING_COLORMAPS_COLORMAPLUTS_HPP
