project:
  type: website
  output-dir: .

website:
  title: "Neuralyzer" # Title of the website
 # favicon:
  navbar:
    collapse-below: lg
    pinned: true
    right:
      - id: intro
        text: "Introduction"
        href: introduction.qmd

      - text: "Getting Started"
        href: getting-started.qmd
        
      - text: "Learning Resources"
        href: learning-resources/index.qmd
            
      - text: "Reference Guides"
        menu:
          - text: "User Guide"
            href: user_guide/index.qmd
          - text: "Developer Guide"
            href: developer/index.qmd
          - text: "API Reference"
            href: api_reference.qmd

      - icon: github
        href: https://github.com/paulmthompson/WhiskerToolbox
        aria-label: GitHub


  sidebar:
    - title: "Developer Documentation"
      style: "docked"
      contents:
        - developer/index.qmd
        - developer/python_bindings/python_integration.qmd
        - developer/benchmark/benchmarking.qmd
        - developer/building.qmd
        - developer/copilot.qmd
        - developer/contributing_code.qmd
        - developer/fuzz/fuzzing.qmd
        - developer/intro_to_c.qmd
        - developer/analysis/static_analysis.qmd
        - developer/testing/testing.qmd
        - text: "API Reference"
          href: api_reference.qmd
        - section: "Core Libraries"
          contents:
            - developer/CoreGeometry/index.qmd
            - developer/coreplotting/index.qmd
            - developer/Entity/index.qmd
            - section: "Deep Learning"
              href: developer/DeepLearning/index.qmd
              contents:
                - developer/DeepLearning/model_wrapper_guide.qmd
                - developer/DeepLearning/aot_inductor_tutorial.qmd
                - developer/DeepLearning/roadmap.qmd
            - section: "Transforms V2"
              href: developer/transforms_v2/index.qmd
              contents:
                - developer/transforms_v2/architecture.qmd
                - developer/transforms_v2/adding_transforms.qmd
            - section: "ParameterSchema"
              href: developer/ParameterSchema/index.qmd
        - section: "Data Inspectors"
          contents:
            - developer/ui/data_inspectors/tensor_inspector.qmd
            - developer/ui/data_inspectors/digital_event_series_inspector.qmd
        - section: "Data Management"
          contents:
            - developer/DataManager/data_manager.qmd
            - developer/DataManager/file_io.qmd
            - developer/DataManager/data_structures.qmd
            - developer/DataManager/binary_loading_performance.qmd
            - developer/DataManager/generic_time_series.qmd
            - developer/DataManager/storage_architecture.qmd
            - developer/DataManager/storage_testing_roadmap.qmd
            - developer/DataManager/storage_benchmarking_roadmap.qmd
            - section: "Command Architecture"
              href: developer/DataManager/Commands/index.qmd
              contents:
                - developer/DataManager/Commands/roadmap.qmd
                - developer/DataManager/Commands/core_types.qmd
                - developer/DataManager/Commands/sequence_execution.qmd
                - developer/DataManager/Commands/get_entity_ids_in_range.qmd
                - developer/DataManager/Commands/commands.qmd
                - developer/DataManager/Commands/validation.qmd
                - developer/DataManager/Commands/command_introspection.qmd
        - section: "Triage Session"
          contents:
            - developer/TriageSession/index.qmd
        - section: "User Interface"
          contents:
            - developer/ui/data_manager/data_manager_widget.qmd
            - developer/ui/data_transform/data_transform_widget.qmd
            - developer/ui/media_widget/media_widget.qmd
            - developer/ui/TriageSession_Widget/index.qmd
            - section: "Features"
              href: developer/ui/Features/overview.qmd
              contents:
                  - developer/ui/Features/Collapsible_Widget.qmd
            - text: "AutoParam System"
              href: developer/ui/autoparam.qmd
            - section: "Plot Widgets"
              href: developer/ui/Plots/plot_widget_guide.md
              contents:
                  - section: "Common"
                    contents:
                      - developer/ui/Plots/Common/ColormapControls/index.qmd
                      - developer/ui/Plots/Common/TooltipManager/index.qmd
                  - developer/ui/Plots/3DPlot/index.qmd
                  - developer/ui/Plots/ACFWidget/index.qmd
                  - developer/ui/Plots/DataViewerWidget/index.qmd
                  - developer/ui/Plots/EventPlotWidget/index.qmd
                  - developer/ui/Plots/HeatmapWidget/index.qmd
                  - developer/ui/Plots/LinePlotWidget/index.qmd
                  - developer/ui/Plots/OnionSkinViewWidget/index.qmd
                  - developer/ui/Plots/PSTHWidget/index.qmd
                  - developer/ui/Plots/ScatterPlotWidget/index.qmd
                  - developer/ui/Plots/SpectrogramWidget/index.qmd
                  - developer/ui/Plots/TemporalProjectionViewWidget/index.qmd

    - title: "Learning Resources"
      contents:
        - learning-resources/index.qmd
        - section: "Tutorials"
          contents:
            - text: "Keypoint Labeling"
              href: examples/keypoint_labeling.qmd
        - section: "Concepts"
          contents: 
            - concepts/timeframe.qmd
        - section: "How-to Guides"
          contents:
            - text: "Label Creation"
              href: labeling/keypoint.qmd
            - text: "Mask Creation"
              href: labeling/mask.qmd
            - text: "Video Import"
              href: examples/video_import.qmd
            - text: "Image Stack Import"
              href: examples/image_stack_import.qmd
            - text: "Load Tabular Binary Events"
              href: examples/tabular_binary_events.qmd
            - text: "Triage Line Data"
              href: learning-resources/how-to/triage_line_data.qmd
            - text: "Label Video Intervals"
              href: learning-resources/how-to/label_video_intervals.qmd

    - title: "User Guide"
      style: "docked"
      collapse-level: 1
      contents:
        - text: "Introduction"
          href: user_guide/index.qmd
        - section: "Acquisition Systems"
          href: user_guide/acquisition_systems/index.qmd
          contents:
            - user_guide/acquisition_systems/intan.qmd
            - user_guide/acquisition_systems/openephys.qmd
            - user_guide/acquisition_systems/labjack.qmd
            - user_guide/acquisition_systems/doric.qmd
            - user_guide/acquisition_systems/generic_hdf5.qmd
            - user_guide/acquisition_systems/generic_binary.qmd
            - user_guide/acquisition_systems/image_stacks.qmd
            - user_guide/acquisition_systems/spikesorter.qmd
        - section: "Data Loading"
          href: user_guide/data_loading/index.qmd
          contents:
            - user_guide/data_loading/JSON_loading.qmd
            - user_guide/data_loading/Point_Loading.qmd
            - user_guide/data_loading/Mask_Loading.qmd
            - user_guide/data_loading/Video_Loading.qmd
            - user_guide/data_loading/Image_Loading.qmd
            - user_guide/data_loading/Line_Loading.qmd
            - user_guide/data_loading/Tensor_Loading.qmd
        - section: "Media Viewer"
          contents:
            - user_guide/media_viewer/overview.qmd
            - user_guide/media_viewer/process.qmd
            - user_guide/media_viewer/points.qmd
            - user_guide/media_viewer/masks.qmd
            - user_guide/media_viewer/intervals.qmd
            - user_guide/media_viewer/lines.qmd
            - user_guide/media_viewer/tensors.qmd
        - section: "Image Processing"
          href: user_guide/image_processing/index.qmd
          contents:
            - user_guide/image_processing/contrast.qmd
            - user_guide/image_processing/gamma.qmd
            - user_guide/image_processing/sharpening.qmd
            - user_guide/image_processing/clahe.qmd
            - user_guide/image_processing/bilateral_filter.qmd
        - section: "Data Viewer"
          contents:
            - user_guide/data_viewer/overview.qmd
        - section: "Plot Widgets"
          href: user_guide/Plots/index.qmd
          contents:
            - user_guide/Plots/3DPlot/index.qmd
            - user_guide/Plots/ACFWidget/index.qmd
            - user_guide/Plots/DataViewerWidget/index.qmd
            - user_guide/Plots/EventPlotWidget/index.qmd
            - user_guide/Plots/HeatmapWidget/index.qmd
            - user_guide/Plots/LinePlotWidget/index.qmd
            - user_guide/Plots/OnionSkinViewWidget/index.qmd
            - user_guide/Plots/PSTHWidget/index.qmd
            - user_guide/Plots/ScatterPlotWidget/index.qmd
            - user_guide/Plots/SpectrogramWidget/index.qmd
            - user_guide/Plots/TemporalProjectionViewWidget/index.qmd
        - section: "Data Manager"
          contents:
            - user_guide/data_manager/overview.qmd
        - section: "Data Transformations"
          contents:
            - user_guide/data_transformations/overview.qmd
            - text: "Transform Widget"
              href: user_guide/data_transformations/transforms_v2_widget.qmd
        - section: "Data Inspectors"
          contents:
            - text: "Tensor Inspector"
              href: user_guide/data_inspectors/tensor_inspector.qmd
            - user_guide/data_transformations/analog_event_threshold.qmd
            - user_guide/data_transformations/analog_interval_threshold.qmd
            - user_guide/data_transformations/digital_interval_group.qmd
            - user_guide/data_transformations/analog_hilbert_phase.qmd
            - user_guide/data_transformations/line_angle.qmd
            - user_guide/data_transformations/line_clip.qmd
            - user_guide/data_transformations/line_curvature.qmd
            - user_guide/data_transformations/line_resample.qmd
            - user_guide/data_transformations/extract_line_subsegment.qmd
            - user_guide/data_transformations/calculate_line_to_point_distance.qmd
            - user_guide/data_transformations/extract_point_from_line.qmd
            - user_guide/data_transformations/mask_area.qmd
            - user_guide/data_transformations/mask_centroid.qmd
            - user_guide/data_transformations/calculate_mask_principal_axis.qmd
            - user_guide/data_transformations/remove_small_connected_components.qmd
            - user_guide/data_transformations/skeletonize_mask.qmd
            - user_guide/data_transformations/fill_mask_holes.qmd
            - user_guide/data_transformations/apply_median_filter.qmd
        - section: "Deep Learning"
          contents:
            - user_guide/deep_learning/deep_learning_widget.qmd
        - section: "Machine Learning"
          contents:
            - user_guide/machine_learning/ML_intro.qmd
            - user_guide/machine_learning/Naive_Bayes.qmd
            - user_guide/machine_learning/Random_Forest.qmd
        - section: "Export"
          contents:
            - user_guide/export/video_export.qmd
        - section: "Behavioral Modules"
          contents:
            - user_guide/behaviors/whisker.qmd
            - user_guide/behaviors/tongue.qmd
        - section: "Triage Session"
          contents:
            - user_guide/triage_session/overview.qmd
        - section: "Python Console"
          contents:
            - user_guide/python_console.qmd


format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual
