
if (enableAddressSanitizer)
    if (WIN32)
        if (MSVC)
            set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} /fsanitize=address")
            add_compile_definitions(_DISABLE_STRING_ANNOTATION=1 _DISABLE_VECTOR_ANNOTATION=1)
            message(STATUS "This is a Debug build for MSVC, enabling address sanitizer")
        endif()
    endif()

    if (UNIX)
        if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
            message(STATUS "Enabling address sanitizer for Clang (both Debug and Release)")
            set(SANITIZER_FLAGS_ASAN "-fsanitize=address")
            set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} ${SANITIZER_FLAGS_ASAN}")
            set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} ${SANITIZER_FLAGS_ASAN}")
            set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${SANITIZER_FLAGS_ASAN}")
            set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} ${SANITIZER_FLAGS_ASAN}")
            
            # UBSan only in Debug to avoid issues with dependencies
            message(STATUS "Enabling undefined behavior sanitizer for Clang (Debug only)")
            set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -fsanitize=undefined")
        elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
            message(STATUS "Enabling address sanitizer for GCC (both Debug and Release)")
            set(SANITIZER_FLAGS_ASAN "-fsanitize=address -fPIC")
            set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} ${SANITIZER_FLAGS_ASAN}")
            set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} ${SANITIZER_FLAGS_ASAN}")
            set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${SANITIZER_FLAGS_ASAN}")
            set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} ${SANITIZER_FLAGS_ASAN}")
            
            # UBSan only in Debug to avoid issues with dependencies
            message(STATUS "Enabling undefined behavior sanitizer for GCC (Debug only)")
            set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -fsanitize=undefined")
        endif()
    endif()
endif()
